language: ruby
rvm:
- 2.5.0

before_script:
 - chmod +x ./build.sh
script: ./build.sh

branches:
  only:
  - dev

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  target-branch: master
