language: ruby
rvm:
- 2.5.0
before_script:
- chmod +x ./build.sh
script: "./build.sh"
branches:
  only:
  - dev
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: oJ1BxSBOcB4W5fvoOfvq8UFeqGLT/G7bddH49+WPcEBYuZqsPH8MShmauVKgfF5oxuxzr2g6ZrygzkLbfDJQuGDuE1rX3rHgUiji3rkmHKEV9jiZ93MpbDejnmiV31YZGy5ohAhSLKIXnMpmX1dvWLthjGd09tmfYufOBRbRxKIM3EbpEuHXRVHBy+noYNadeeMTxMGpT085sm0Pb4Pxerd5X67biBXGT9xaPzSlTtsHoL8wRg130cWFe+muOLBaeNMhOKuF728dWzAaHOzprKoQxwDd9eza+YjKkrXBCxpPHQNdv4zBnNUULYNdDyO6FOK5xHPJlaf82Bo6q2MIhjdMZOV9qHEz98pd0bI6jZlWbvb961Qv/83WbFndWna2y947n4iygtcLmi9tOlsD2CQa5vkobv8KtL3DE3ktuwr9pyhjwXfQbT/ABmA1aNLn3cZUwG73rG74Nehvd1U+yEEAeY9isXGITj+finHBlJrk0fSpkyPVnhKUjNp5wp8gVqOirJNcvQiqHyevOKV9sevEZtgLu6qMcK0dNXMbE6CJv2Ig2DRtIUinHxTVaJTxwygGo8vEFf9hXm7TxswGs0qlTF7rqQl80/1ociKuTDiAzs6bXATwaUELG8DiwRjxINkQDAljPk3oKCkGmho+kwBIWXhXBU8nE91u2KVMBRc=
sudo: false
