language: ruby
branches:
  only:
  - dev
rvm:
- 2.5.0
cache: bundler
install:
- bundle install
script:
- "sh ./build.sh"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  target-branch: master
