# Dependencies
markdown:         kramdown

# Setup
title:            coding @ dusk
tagline:          'rambles about code, cats, and other nonsense.'
description:      'rambles about code, cats, and other nonsense.'
url:              https://alycejenni.github.io
baseurl:          ''
version:          0.1

# plugins and themes
paginate:         5
paginate_path:    '/page:num'
excerpt_separator:  <!--more-->
permalink: /:year/:month/:title/

theme: 'jekyll-theme-hydeout'

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-category-pages

# author
author:
  name:           'Alice Butcher'
  github:         'alycejenni'
  twitter:        'alicejelly'
github:
  repo: https://github.com/alycejenni/alycejenni.github.io
disqus:
  shortname:      'alycejenni'


# plugin settings
sidebar_home_link:  true
category_layout: category.html

exclude: [vendor]
