# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            coding @ dusk
tagline:          'rambles about code, cats, and other nonsense.'
description:      'rambles about code, cats, and other nonsense.'
url:              https://alycejenni.github.io
baseurl:          ''
version:          0.1

# plugins and themes
paginate:         5
paginate_path:    '/page:num'

remote_theme: 'fongandrew/hydeout'

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# author
author:
  name:           'Alice Butcher'
  github:         'alycejenni'
  twitter:        'alicejelly'
github:
  repo: https://github.com/alycejenni/alycejenni.github.io
disqus:
  shortname:      'alycejenni'


# hydeout
sidebar_home_link:  true
